import type { Recordable } from './tool'
import type {
  WebBuilderMode,
  WebBuilderFormat,
  //   WebBuilderTarget,
} from './web-builder'

type ManifestServerProxyPathRewrite = {
  regular: RegExp | string
  replacement: string
}[]

type ManifestExternals =
  | string[]
  | {
      name: string
      globalName?: string
      regular?: boolean
    }[]

export interface LoadManifestOptions {
  /**
   * manifest file storage directory
   * @default process.cwd()
   */
  root?: string

  /**
   * manifest filename
   * @default project-manifest.json
   */
  manifestFileName?: string

  /**
   * mode
   */
  mode?: WebBuilderMode
}

export type ManifestExportsType = Recordable<{
  [(key in (WebBuilderFormat & 'name')) | 'importmap']?: string
}>

export type ManifestImportmapType = {
  packageName?: string
  filename?: {
    esm: string
    system: string
  }
}

export interface WebBuilderProjectConfig {
  /**
   * application entry file.
   */
  entries: string[]

  /**
   * Build tools publicPath configuration.
   */
  publicPath?: string
  /**
   * Shared Dependencies & Common Dependencies.
   */
  externals?: ManifestExternals
  /**
   * local server configuration
   */
  server?: ManifestServer

  /**
   * Build product output directory
   */
  outDir?: string

  sourcemap?: boolean

  /**
   * Build product output format
   */
  formats?: WebBuilderFormat[]

  /**
   * App export description
   */
  exports?: ManifestExportsType
}

// This file is automatically generated, please do not modify it.
export interface WebBuilderManifest extends WebBuilderProjectConfig {
  /**
   * The version number of the manifest.
   */
  schemaVersion: string
  /**
   * env configuration for different environments.
   */
  env?: {
    [pattern: string]: Partial<WebBuilderProjectConfig> /* Patterns: [a-z]+ */
  }
}

export type ManifestServerProxy = {
  url: string
  target: string
  secure?: boolean
  changeOrigin?: boolean
  pathRewrite?: ManifestServerProxyPathRewrite
}[]

export interface ManifestServer {
  port?: number
  proxy?: ManifestServerProxy
  host?: string | boolean
}
